name: CD (ACR Push)

"on":
  push:
    branches:
      - main

jobs:
  cd-status:
    runs-on: ubuntu-latest
    steps:
      - name: CD status
        run: echo "CD is configured. Build+push runs only when Azure/ACR secrets are set."

  build-and-push:
    runs-on: ubuntu-latest

    # Job uruchomi się TYLKO gdy:
    # - wszystkie sekrety są ustawione
    # - i subscription id NIE jest tenantId (bo wtedy azure/login polegnie)
    if: >
      ${{
        secrets.AZURE_CLIENT_ID != '' &&
        secrets.AZURE_TENANT_ID != '' &&
        secrets.AZURE_SUBSCRIPTION_ID != '' &&
        secrets.ACR_NAME != '' &&
        secrets.ACR_LOGIN_SERVER != '' &&
        secrets.AZURE_SUBSCRIPTION_ID != '785acb66-71d5-49f6-b377-37a292991048'
      }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/projekt-devops:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/projekt-devops:latest
